name: Windows CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: 2f20dab76e667644c2a8a3a8b93685ed0bca3b2539270516a6d00e5a770928a9
